### ISSUE TITLE
solicitud de colaboracion

### ISSUE THREAD

**Issue by acostamar** [acostamar/base#3]
solicito colaboracion en el nuevo proyecto de BD My sql @Esther-byte290

**Comment by Esther-byte290** [comment]
claro que si, guapi!!!!!

**Comment by acostamar** [comment]
Estoy viendo tu mensaje ahora mismo que estoy repasando..y que risa me ha dado!!!! jajajaja...
Ya tengo instalado el github desktop...ahora a practicar a ver si logro recordar lo que vimos hoy!!!

**Comment by Esther-byte290** [comment]
Sí necesitas cualquier cosilla, alguna duda... Dímelo.
